name-template: "Mandarin $NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"
categories:
  - title: "ğŸš€Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ğŸ›Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ğŸ§°Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "maintenance"
      - "technical"
exclude-labels:
  - "exclude"
change-template: "- $TITLE (@$AUTHOR | PR #$NUMBER)"
template: |
  # Changes

  $CHANGES
